export const AUTH_START = 'AUTH_START';

export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';

export const AUTH_ATTEMPT = 'AUTH_ATTEMPT';


export const AUTH_INITIALIZE_CHECKAUTH_TIMEOUT = 'AUTH_INITIALIZE_CHECKAUTH_TIMEOUT';

export const AUTH_INITIALIZE_AUTHCHECK_STATE = 'AUTH_INITIALIZE_AUTHCHECK_STATE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'; //approach do professor, dos redirects...


// export const BURGER_CREATED_WITHOUT_AUTH = 'BURGER_CREATED_WITHOUT_AUTH'; ///meu approach, approach antigo de fazer os REDIRECTS FUNCIONAREM...






// export const BURGER_FINISHED_PURCHASING = 'BURGER_FINISHED_PURCHASING';