export const AUTH_START = 'AUTH_START';

export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';



export const BURGER_CREATED_WITHOUT_AUTH = 'BURGER_CREATED_WITHOUT_AUTH';






export const BURGER_FINISHED_PURCHASING = 'BURGER_FINISHED_PURCHASING';