export const INGREDIENT_ADD = 'INGREDIENT_ADD';

export const INGREDIENT_REMOVE = 'INGREDIENT_REMOVE';

export const ORDER_INITIAL_INGREDIENTS_GET = 'ORDER_INITIAL_INGREDIENTS_GET';

export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const SIDEDRAWER_CLOSE = 'SIDEDRAWER_CLOSE';